# Reference values seeded by ARW at startup when a preset is selected.
# Explicit environment variables override these.

[eco]
ARW_HTTP_MAX_CONC = 256
ARW_ACTIONS_QUEUE_MAX = 256
ARW_CONTEXT_K = 12
ARW_CONTEXT_EXPAND_PER_SEED = 2
ARW_CONTEXT_DIVERSITY_LAMBDA = 0.65
ARW_CONTEXT_MIN_SCORE = 0.08
ARW_CONTEXT_LANES_DEFAULT = "semantic,procedural"
ARW_CONTEXT_LANE_BONUS = 0.08
ARW_CONTEXT_EXPAND_QUERY = 0
ARW_CONTEXT_EXPAND_QUERY_TOP_K = 3
ARW_CONTEXT_SCORER = "mmrd"
ARW_CONTEXT_STREAM_DEFAULT = 0
ARW_CONTEXT_COVERAGE_MAX_ITERS = 2
ARW_REHYDRATE_FILE_HEAD_KB = 32
ARW_ROUTE_STATS_COALESCE_MS = 350
ARW_ROUTE_STATS_PUBLISH_MS = 2500
ARW_MODELS_METRICS_COALESCE_MS = 350
ARW_MODELS_METRICS_PUBLISH_MS = 2500

[balanced]
ARW_HTTP_MAX_CONC = 1024
ARW_ACTIONS_QUEUE_MAX = 1024
ARW_CONTEXT_K = 18
ARW_CONTEXT_EXPAND_PER_SEED = 3
ARW_CONTEXT_DIVERSITY_LAMBDA = 0.70
ARW_CONTEXT_MIN_SCORE = 0.10
ARW_CONTEXT_LANES_DEFAULT = "semantic,procedural,episodic"
ARW_CONTEXT_LANE_BONUS = 0.06
ARW_CONTEXT_EXPAND_QUERY = 1
ARW_CONTEXT_EXPAND_QUERY_TOP_K = 4
ARW_CONTEXT_SCORER = "mmrd"
ARW_CONTEXT_STREAM_DEFAULT = 1
ARW_CONTEXT_COVERAGE_MAX_ITERS = 2
ARW_REHYDRATE_FILE_HEAD_KB = 64
ARW_ROUTE_STATS_COALESCE_MS = 250
ARW_ROUTE_STATS_PUBLISH_MS = 2000
ARW_MODELS_METRICS_COALESCE_MS = 250
ARW_MODELS_METRICS_PUBLISH_MS = 2000

[performance]
ARW_HTTP_MAX_CONC = 4096
ARW_ACTIONS_QUEUE_MAX = 4096
ARW_CONTEXT_K = 24
ARW_CONTEXT_EXPAND_PER_SEED = 4
ARW_CONTEXT_DIVERSITY_LAMBDA = 0.74
ARW_CONTEXT_MIN_SCORE = 0.12
ARW_CONTEXT_LANES_DEFAULT = "semantic,procedural,episodic"
ARW_CONTEXT_LANE_BONUS = 0.05
ARW_CONTEXT_EXPAND_QUERY = 1
ARW_CONTEXT_EXPAND_QUERY_TOP_K = 5
ARW_CONTEXT_SCORER = "mmrd"
ARW_CONTEXT_STREAM_DEFAULT = 1
ARW_CONTEXT_COVERAGE_MAX_ITERS = 3
ARW_REHYDRATE_FILE_HEAD_KB = 96
ARW_ROUTE_STATS_COALESCE_MS = 150
ARW_ROUTE_STATS_PUBLISH_MS = 1500
ARW_MODELS_METRICS_COALESCE_MS = 150
ARW_MODELS_METRICS_PUBLISH_MS = 1500

[turbo]
ARW_HTTP_MAX_CONC = 16384
ARW_ACTIONS_QUEUE_MAX = 16384
ARW_CONTEXT_K = 32
ARW_CONTEXT_EXPAND_PER_SEED = 4
ARW_CONTEXT_DIVERSITY_LAMBDA = 0.78
ARW_CONTEXT_MIN_SCORE = 0.15
ARW_CONTEXT_LANES_DEFAULT = "semantic,procedural,episodic,insight"
ARW_CONTEXT_LANE_BONUS = 0.04
ARW_CONTEXT_EXPAND_QUERY = 1
ARW_CONTEXT_EXPAND_QUERY_TOP_K = 6
ARW_CONTEXT_SCORER = "mmrd"
ARW_CONTEXT_STREAM_DEFAULT = 1
ARW_CONTEXT_COVERAGE_MAX_ITERS = 3
ARW_REHYDRATE_FILE_HEAD_KB = 128
ARW_ROUTE_STATS_COALESCE_MS = 100
ARW_ROUTE_STATS_PUBLISH_MS = 1000
ARW_MODELS_METRICS_COALESCE_MS = 100
ARW_MODELS_METRICS_PUBLISH_MS = 1000
