# Reference values seeded by ARW at startup when a preset is selected.
# Explicit environment variables override these.

[eco]
ARW_HTTP_MAX_CONC = 256
ARW_ACTIONS_QUEUE_MAX = 256
ARW_CONTEXT_SCAN_LIMIT = 120
ARW_REHYDRATE_FILE_HEAD_KB = 32
ARW_ROUTE_STATS_COALESCE_MS = 350
ARW_ROUTE_STATS_PUBLISH_MS = 2500
ARW_MODELS_METRICS_COALESCE_MS = 350
ARW_MODELS_METRICS_PUBLISH_MS = 2500

[balanced]
ARW_HTTP_MAX_CONC = 1024
ARW_ACTIONS_QUEUE_MAX = 1024
ARW_CONTEXT_SCAN_LIMIT = 200
ARW_REHYDRATE_FILE_HEAD_KB = 64
ARW_ROUTE_STATS_COALESCE_MS = 250
ARW_ROUTE_STATS_PUBLISH_MS = 2000
ARW_MODELS_METRICS_COALESCE_MS = 250
ARW_MODELS_METRICS_PUBLISH_MS = 2000

[performance]
ARW_HTTP_MAX_CONC = 4096
ARW_ACTIONS_QUEUE_MAX = 4096
ARW_CONTEXT_SCAN_LIMIT = 300
ARW_REHYDRATE_FILE_HEAD_KB = 96
ARW_ROUTE_STATS_COALESCE_MS = 150
ARW_ROUTE_STATS_PUBLISH_MS = 1500
ARW_MODELS_METRICS_COALESCE_MS = 150
ARW_MODELS_METRICS_PUBLISH_MS = 1500

[turbo]
ARW_HTTP_MAX_CONC = 16384
ARW_ACTIONS_QUEUE_MAX = 16384
ARW_CONTEXT_SCAN_LIMIT = 500
ARW_REHYDRATE_FILE_HEAD_KB = 128
ARW_ROUTE_STATS_COALESCE_MS = 100
ARW_ROUTE_STATS_PUBLISH_MS = 1000
ARW_MODELS_METRICS_COALESCE_MS = 100
ARW_MODELS_METRICS_PUBLISH_MS = 1000

