version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    # Avoid excessive splitting: group minor+patch updates
    groups:
      rust-minor-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
