version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/Agent_Hub"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
  - package-ecosystem: "github-actions"
    directory: "/Agent_Hub"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
