accept = [200, 206, 429]
max_retries = 2
retry_wait_time = 2
method = "get"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
exclude = [
  "https://github.com/t3hw00t/ARW/pull/", # PR links may be transient
  "^http://127\\.0\\.0\\.1(:\\d+)?(/.*)?$", # local dev links
  "^https://ghcr\\.io/.*$",                  # GHCR landing URLs may 404
  "^https://t3hw00t\\.github\\.io/ARW/.*$", # site paths may lag until gh-pages updates
  "^https://github\\.com/t3hw00t/ARW/releases/latest/download/.*$", # assets exist only after releases
  'https://github.com/t3hw00t/ARW/releases/download/v0.1.3/\$msi',
  'https://github.com/t3hw00t/ARW/releases/download/v0.1.3/\$msiArm64',
  "https://www.npmjs.com/package/@arw/client",
]
headers = [
  "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
  "Accept-Language: en-US,en;q=0.9"
]
