[advisories]
ignore = [
  { id = "RUSTSEC-2024-0370", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0410", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0411", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0412", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0413", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0414", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0415", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0416", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0417", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0418", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0419", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0420", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0429", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" },
  { id = "RUSTSEC-2024-0436", reason = "GTK3 bindings remain until upstream GTK4 migration lands in wry/tauri" }
]
