[advisories]
vulnerability = "deny"
unmaintained = "warn"
unsound = "warn"
yanked = "warn"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "warn"
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "OpenSSL"
]
exceptions = []
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
