[advisories]
# Advisory severities
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
unsound = "deny"
ignore = []

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MPL-2.0",
  "CC0-1.0", # required for tiny-keccak via cedar-policy (transitive build-time dependency)
  "Unicode-DFS-2016",
  "Unicode-3.0",
  "Apache-2.0 WITH LLVM-exception",
  "CDLA-Permissive-2.0",
  "Unlicense",
  "Zlib",
]
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/*"]
