site_name: ARW
repo_url: https://github.com/t3hw00t/Agent_Hub
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.tabs.link
extra_css:
  - css/overrides.css
docs_dir: docs
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
nav:
  - Home: index.md
  - Tutorials:
      - Try ARW in 2 Minutes: guide/quickstart.md
  - How‑to:
      - Models Download: guide/models_download.md
      - Subscribe to Events (SSE): guide/events_sse.md
      - Security Hardening: guide/security_hardening.md
      - Network Posture: guide/network_posture.md
      - Desktop Launcher: guide/launcher.md
      - Screenshots: guide/screenshots.md
      - Admin Endpoints: guide/admin_endpoints.md
      - Troubleshooting: guide/troubleshooting.md
  - Reference:
      - API Reference: reference/api.md
      - Configuration: CONFIGURATION.md
      - CLI Reference: reference/cli.md
      - Schemas:
          - API and Schema: API_AND_SCHEMA.md
          - Egress Schemas: api/egress_schemas.md
          - Cluster Schemas: api/cluster_schemas.md
          - Memory & World Schemas: api/memory_world_schemas.md
          - JSON Schemas: reference/schemas.md
      - Support Matrix: reference/support_matrix.md
      - Telemetry & Privacy: reference/telemetry_privacy.md
      - Trust Boundaries: reference/trust_boundaries.md
      - Glossary: GLOSSARY.md
  - Explanations:
      - Unified Object Graph: architecture/object_graph.md
      - Events Vocabulary: architecture/events_vocabulary.md
      - Self‑Model (Metacognition): architecture/self_model.md
      - Logic Units: architecture/logic_units.md
      - Egress Firewall: architecture/egress_firewall.md
      - Lightweight Mitigations: architecture/lightweight_mitigations.md
      - Config Patch Engine: architecture/config_patch_engine.md
      - Experiment Orchestrator: architecture/experiment_orchestrator.md
      - Observability (OTel): architecture/observability_otel.md
      - AppSec Harness: architecture/appsec_harness.md
      - Compliance Mode: architecture/compliance_mode.md
      - Supply‑Chain Trust: architecture/supply_chain_trust.md
      - Federated Clustering: architecture/cluster_federation.md
      - Scheduler & Governor: architecture/scheduler_governor.md
      - Durability & Offline: architecture/durability.md
      - Identity & Tenancy: architecture/identity_tenancy.md
      - Capability & Consent Ledger: architecture/capability_consent_ledger.md
      - Artifacts & Provenance: architecture/artifacts_provenance.md
      - Budgets & Context: architecture/budgets_context.md
      - Memory Lifecycle: architecture/memory_lifecycle.md
      - Context Working Set: architecture/context_working_set.md
      - Error & Event Taxonomy: architecture/error_taxonomy.md
      - Versioning & Migration: architecture/versioning_migration.md
      - Scheduling & Backpressure: architecture/scheduling_backpressure.md
      - Data Governance & Privacy: architecture/data_governance.md
      - Replay & Time Travel: architecture/replay_time_travel.md
      - Naming & IDs: architecture/naming_ids.md
      - UX Invariants: architecture/ux_invariants.md
  - Contribute:
      - Overview: developer/index.md
      - Docs Style (Diátaxis): developer/docs_style.md
      - Status: developer/status.md
      - Tasks: developer/tasks.md
      - Stability Freeze: developer/stability.md
      - CI: developer/ci.md
      - Style: developer/style.md
      - Security: developer/SECURITY.md
      - Windows Compatibility Gate: developer/windows-compat-gate.md
      - Windows Start Validation: developer/windows-start-validation.md
      - Plugin ABI & Trust: developer/plugin_abi_trust.md
      - Contract Tests: developer/contract_tests.md
      - Assisted Coding:
          - Working Agreement: ai/ASSISTED_DEV_GUIDE.md
          - Repo Map: ai/REPO_MAP.md
          - Change Plan Template: ai/CHANGE_PLAN_TEMPLATE.md
  - AI:
      - Assistants Index: ai/ai_index.md
      - Contracts: ai/ai_contracts.md
      - Prompts Policy: ai/ai_prompts.md
  - Release notes:
      - Release Notes: release_notes.md
      - Roadmap: ROADMAP.md
      - Interface Roadmap: INTERFACE_ROADMAP.md
      - Backlog: BACKLOG.md
