site_name: Agent Hub (ARW)
site_description: "Your private AI control room that can scale and share when you choose. Run a local-first, privacy-first team of AI helpers — and only pool compute with trusted peers when needed."
repo_url: https://github.com/t3hw00t/ARW
site_url: https://t3hw00t.github.io/ARW/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs/
extra_css:
  - css/tokens.css
  - css/overrides.css
extra_javascript:
  - static/status-badges.js
docs_dir: docs
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
nav:
  - Home: index.md
  - Overview:
      - Features: FEATURES.md
      - Concepts: guide/concepts.md
  - Tutorials:
      - Quickstart: guide/quickstart.md
      - Shortcuts: guide/shortcuts.md
  - How‑to:
      - Docker: guide/docker.md
      - Deployment & Isolation: guide/deployment.md
      - Dev TLS: guide/dev_tls.md
      - Release Guide: guide/release.md
      - Kubernetes (Helm): guide/kubernetes.md
      - Reverse Proxy: guide/reverse_proxy.md
      - Models Download: guide/models_download.md
      - Subscribe to Events (SSE): guide/events_sse.md
      - Events & Logs Windows: guide/events_logs.md
      - Command Palette: guide/command_palette.md
      - Workflow Views & Sidecar: guide/workflow_views.md
      - Scaling & Sharing: guide/scaling_sharing.md
      - Security Hardening: guide/security_hardening.md
      - Network Posture: guide/network_posture.md
      - Egress Settings: guide/egress_settings.md
      - Desktop Launcher: guide/launcher.md
      - Windows:
          - Install & Launcher: guide/windows_install.md
          - Download (x64 MSI): https://github.com/t3hw00t/ARW/releases/latest/download/arw-launcher-x64.msi
          - Download (ARM64 MSI): https://github.com/t3hw00t/ARW/releases/latest/download/arw-launcher-arm64.msi
      - macOS:
          - Install & Launcher: guide/macos_install.md
      - Screenshots: guide/screenshots.md
      - Screenshots Gallery: guide/gallery.md
      - CLI Guide: guide/cli.md
      - Debug UI: guide/debug_ui.md
      - Offline & Sync: guide/offline_sync.md
      - Plugins: guide/plugins.md
      - Policy Permissions: guide/policy_permissions.md
      - Policy (ABAC Facade): guide/policy_abac.md
      - Connectors: guide/connectors.md
      - Projects UI: guide/projects_ui.md
      - Recipes: guide/recipes.md
      - Runtime Matrix: guide/runtime_matrix.md
      - Vision Runtime Preview: guide/vision_runtime.md
      - Security Posture: guide/security_posture.md
      - Threat Model: guide/threat_model.md
      - UI Architecture: guide/ui_architecture.md
      - UI Flows (ASCII): guide/ui_flows.md
      - Compatibility: guide/compatibility.md
      - Design System: guide/design_system.md
      - gRPC: guide/grpc.md
      - Cost & Quotas: guide/cost_quota.md
      - Context Recipes: guide/context_recipes.md
      - Metrics & Insights: guide/METRICS_AND_INSIGHTS.md
      - Monitoring & Alerts: ops/monitoring.md
      - Cluster Runbook: ops/cluster_runbook.md
      - Alerting (Prometheus): ALERTING.md
      - Trial Planning: ops/trial_readiness.md
      - Trial Runbook: ops/trial_runbook.md
      - Participant Quickstart: ops/trial_quickstart.md
      - Facilitator Checklist: ops/trial_facilitator_checklist.md
      - Trial Dossier:
          - Overview: ops/trials/README.md
          - Daily Log Template: ops/trials/daily_log_template.md
          - Stand-up Template: ops/trials/standup_template.md
          - Dashboard Snapshot Guide: ops/trials/dashboard_snapshot.md
          - Approvals Lane Guide: ops/trials/approvals_lane_guide.md
          - Onboarding Email Template: ops/trials/onboarding_email_template.md
          - Screenshot Checklist: ops/trials/screenshots/README.md
          - Autonomy Rollback Playbook: ops/trials/autonomy_rollback_playbook.md
      - Chat Backends: guide/chat_backends.md
      - Guardrails Checks: guide/guardrails.md
      - Correlation & Attribution: guide/correlation.md
      - Flows (Logic Units): guide/flows.md
      - Feedback Engine: guide/feedback_engine.md
      - Logic Units Library: guide/logic_units_library.md
      - Evaluation Harness: guide/eval_harness.md
      - Experiments (A/B): guide/experiments_ab.md
      - Performance & Reasoning Playbook: guide/performance_reasoning_playbook.md
      - Research Watcher: guide/research_watcher.md
      - Human‑in‑the‑Loop: guide/human_in_loop.md
      - Interactive Performance Config: guide/interactive_performance.md
      - Interactive Performance Bench: guide/interactive_bench.md
      - Performance Presets: guide/performance_presets.md
      - Training Park: guide/training_park.md
      - Context Telemetry Checklist: guide/context_telemetry_checklist.md
      - Context Scenario Harness: guide/context_harness.md
      - Admin Endpoints: guide/admin_endpoints.md
      - Troubleshooting: guide/troubleshooting.md
  - Reference:
      - API Reference: reference/api.md
      - Clients: reference/clients.md
      - Models Types: reference/models_types.md
      - Feature Matrix: reference/feature_matrix.md
      - System Components: reference/system_components.md
      - Feature Catalog: reference/feature_catalog.md
      - Event Topics: reference/topics.md
      - Interface Deprecations: reference/deprecations.md
      - Interface Catalog: reference/interface-catalog.md
      - Configuration: CONFIGURATION.md
      - CLI Reference: reference/cli.md
      - Specs Index: reference/specs.md
      - Interface Release Notes: reference/interface-release-notes.md
      - Gating Keys: GATING_KEYS.md
      - Gating Config: reference/gating_config.md
      - Tools:
          - UI Screenshot Tools: reference/tools/ui_screenshot.md
          - Project Notes Tools: reference/tools/project_notes.md
      - Schemas:
          - API and Schema: API_AND_SCHEMA.md
          - Egress Schemas: api/egress_schemas.md
          - Cluster Schemas: api/cluster_schemas.md
          - Memory & World Schemas: api/memory_world_schemas.md
          - JSON Schemas: reference/schemas.md
      - Autonomy Lane Charter: spec/autonomy_lane.md
      - Support Matrix: reference/support_matrix.md
      - Telemetry & Privacy: reference/telemetry_privacy.md
      - Trust Boundaries: reference/trust_boundaries.md
      - Glossary: GLOSSARY.md
      - Expert Alignment Plan: architecture/expert_alignment_plan.md
  - Design:
      - Overview: design/index.md
      - Autonomy Recovery Follow-ups: design/autonomy_recovery_followups.md
      - Trial Visual Kit: design/trial_visual_kit.md
  - Explanations:
      - Unified Object Graph: architecture/object_graph.md
      - Events Vocabulary: architecture/events_vocabulary.md
      - Restructure Handbook: RESTRUCTURE.md
      - Screenshot Capture Pipeline: architecture/screenshot_capture_pipeline.md
      - UI Architecture Options (ASCII): architecture/ui_architecture_options.md
      - Kernel (Journal + CAS): architecture/kernel.md
      - Self‑Model (Metacognition): architecture/self_model.md
      - Logic Units: architecture/logic_units.md
      - Modular Cognitive Stack: architecture/modular_cognitive_stack.md
      - Agent Orchestrator: architecture/agent_orchestrator.md
      - Memory Abstraction Layer: architecture/memory_abstraction.md
      - Memory Overlay Service: architecture/memory_overlay_service.md
      - Egress Firewall: architecture/egress_firewall.md
      - Lightweight Mitigations: architecture/lightweight_mitigations.md
      - Config Patch Engine: architecture/config_patch_engine.md
      - Experiment Orchestrator: architecture/experiment_orchestrator.md
      - Observability (OTel): architecture/observability_otel.md
      - AppSec Harness: architecture/appsec_harness.md
      - Asimov Capsule Guard: architecture/asimov_capsule_guard.md
      - Compliance Mode: architecture/compliance_mode.md
      - Supply‑Chain Trust: architecture/supply_chain_trust.md
      - Federated Clustering: architecture/cluster_federation.md
      - Scheduler & Governor: architecture/scheduler_governor.md
      - Durability & Offline: architecture/durability.md
      - Identity & Tenancy: architecture/identity_tenancy.md
      - Capability & Consent Ledger: architecture/capability_consent_ledger.md
      - Artifacts & Provenance: architecture/artifacts_provenance.md
      - Budgets & Context: architecture/budgets_context.md
      - Memory Lifecycle: architecture/memory_lifecycle.md
      - Context Working Set: architecture/context_working_set.md
      - Error & Event Taxonomy: architecture/error_taxonomy.md
      - Versioning & Migration: architecture/versioning_migration.md
      - Scheduling & Backpressure: architecture/scheduling_backpressure.md
      - Data Governance & Privacy: architecture/data_governance.md
      - Replay & Time Travel: architecture/replay_time_travel.md
      - Naming & IDs: architecture/naming_ids.md
      - UX Invariants: architecture/ux_invariants.md
      - Cache Policy Manifest: architecture/cache_policy.md
      - Performance Guardrails: architecture/performance.md
      - Caching Layers: architecture/caching_layers.md
      - Runtime Layout: architecture/runtime_layout.md
      - SSE Patch Contract: architecture/sse_patch_contract.md
      - Managed llama.cpp Runtime: architecture/managed_llamacpp_runtime.md
      - Managed Runtime Supervisor: architecture/managed_runtime_supervisor.md
      - Multimodal Runtime Plan: architecture/multimodal_runtime_plan.md
  - Contribute:
      - Overview: developer/index.md
      - Build Efficiency: developer/build_efficiency.md
      - Docs Style (Diátaxis): developer/docs_style.md
      - Design Theme: developer/design_theme.md
      - Standards: developer/standards.md
      - UI Kit (Launcher): developer/ui_kit.md
      - ADRs:
          - Index: adr/index.md
          - 0001: adr/0001-design-tokens-ssot.md
          - 0002: adr/0002-events-naming.md
          - Template: adr/_template.md
      - Status: developer/status.md
      - Admin Handoff: developer/admin_handoff.md
      - Handoff Checklist: developer/handoff_checklist.md
      - Tasks: developer/tasks.md
      - Orchestrator Validation: developer/orchestrator_validation.md
      - Stability Freeze: developer/stability.md
      - CI: developer/ci.md
      - Tauri API: developer/tauri_api.md
      - Style: developer/style.md
      - Security: developer/SECURITY.md
      - Windows Compatibility Gate: developer/windows-compat-gate.md
      - Windows Start Validation: developer/windows-start-validation.md
      - Winget Packaging: developer/winget.md
      - Plugin ABI & Trust: developer/plugin_abi_trust.md
      - Contract Tests: developer/contract_tests.md
  - Operations:
      - Systemd Service: ops/systemd_service.md
      - Systemd Overrides: ops/systemd_overrides.md
      - Operations Guide: OPERATIONS.md
  - Appendix:
      - Snippets:
          - HTTP Caching Semantics: snippets/http_caching_semantics.md
          - Grafana GPU Dashboard: snippets/grafana_gpu_dashboard.md
          - Grafana Quick Panels: snippets/grafana_quick_panels.md
          - Prometheus Recording Rules: snippets/prometheus_recording_rules.md
          - Prometheus Alerting Rules: snippets/prometheus_alerting_rules.md
      - Monitoring:
          - Prometheus Recording Rules: snippets/prometheus_recording_rules.md
          - Prometheus Alerting Rules: snippets/prometheus_alerting_rules.md
          - Grafana — Quick Panels: snippets/grafana_quick_panels.md
          - Grafana — GPU/NPU Dashboard: snippets/grafana_gpu_dashboard.md
      - Assisted Coding:
          - Working Agreement: ai/ASSISTED_DEV_GUIDE.md
          - Repo Map: ai/REPO_MAP.md
          - Change Plan Template: ai/CHANGE_PLAN_TEMPLATE.md
  - AI:
      - Assistants Index: ai/ai_index.md
      - Contracts: ai/ai_contracts.md
      - Prompts Policy: ai/ai_prompts.md
  - Release notes:
      - Release Notes: release_notes.md
      - Roadmap: ROADMAP.md
      - Interface Roadmap: INTERFACE_ROADMAP.md
      - Backlog: BACKLOG.md
