site_name: ARW Docs
site_description: "Agents Running Wild — user guide and developer docs"
site_url: ""
repo_url: ""
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - toc.integrate
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - tables
  - attr_list
  - md_in_html
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
nav:
  - Guide:
      - Overview: index.md
      - Quickstart: guide/quickstart.md
      - Metrics & Insights: guide/METRICS_AND_INSIGHTS.md
      - Project Instructions: PROJECT_INSTRUCTIONS.md
      - Features: FEATURES.md
      - Roadmap: ROADMAP.md
      - Deployment: DEPLOYMENT.md
      - Hardware & Models: HARDWARE_AND_MODELS.md
      - Memory & Training: MEMORY_AND_TRAINING.md
      - API & Schema: API_AND_SCHEMA.md
  - Developer:
      - Structure: STRUCTURE.md
      - Developer Guide: developer/index.md
      - CI & Releases: developer/ci.md
      - Style & Harmony: developer/style.md
      - Workspace Status: developer/status.md
      - Security: developer/SECURITY.md
