site_name: ARW
repo_url: https://github.com/t3hw00t/Agent_Hub
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.tabs.link
extra_css:
  - css/overrides.css
docs_dir: docs
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
nav:
  - Home: index.md
  - Architecture:
      - Unified Object Graph: architecture/object_graph.md
      - Events Vocabulary: architecture/events_vocabulary.md
      - Self‑Model (Metacognition): architecture/self_model.md
      - Logic Units: architecture/logic_units.md
      - Config Patch Engine: architecture/config_patch_engine.md
      - Experiment Orchestrator: architecture/experiment_orchestrator.md
      - Observability (OTel): architecture/observability_otel.md
      - AppSec Harness: architecture/appsec_harness.md
      - Compliance Mode: architecture/compliance_mode.md
      - Supply‑Chain Trust: architecture/supply_chain_trust.md
      - Scheduler & Governor: architecture/scheduler_governor.md
      - Durability & Offline: architecture/durability.md
      - Identity & Tenancy: architecture/identity_tenancy.md
      - Capability & Consent Ledger: architecture/capability_consent_ledger.md
      - Artifacts & Provenance: architecture/artifacts_provenance.md
      - Budgets & Context: architecture/budgets_context.md
      - Memory Lifecycle: architecture/memory_lifecycle.md
      - Error & Event Taxonomy: architecture/error_taxonomy.md
      - Versioning & Migration: architecture/versioning_migration.md
      - Scheduling & Backpressure: architecture/scheduling_backpressure.md
      - Data Governance & Privacy: architecture/data_governance.md
      - Replay & Time Travel: architecture/replay_time_travel.md
      - Naming & IDs: architecture/naming_ids.md
      - UX Invariants: architecture/ux_invariants.md
  - User Guide:
      - Quickstart: guide/quickstart.md
      - Concepts: guide/concepts.md
      - UI Architecture: guide/ui_architecture.md
      - Logic Units Library: guide/logic_units_library.md
      - Research Watcher: guide/research_watcher.md
      - Desktop Launcher: guide/launcher.md
      - Compatibility: guide/compatibility.md
      - Features: FEATURES.md
      - Metrics & Insights: guide/METRICS_AND_INSIGHTS.md
      - Models Download: guide/models_download.md
      - Chat Backends: guide/chat_backends.md
      - gRPC: guide/grpc.md
      - Projects UI: guide/projects_ui.md
      - Design System: guide/design_system.md
      - Agent Recipes: guide/recipes.md
      - Context Recipes: guide/context_recipes.md
      - Runtime Matrix: guide/runtime_matrix.md
      - Training Park: guide/training_park.md
      - Plugins & Extensions: guide/plugins.md
      - Permissions & Policies: guide/policy_permissions.md
      - Evaluation Harness: guide/eval_harness.md
      - Human‑in‑the‑Loop: guide/human_in_loop.md
      - Cost & Quotas: guide/cost_quota.md
      - Offline & Sync: guide/offline_sync.md
      - Threat Model: guide/threat_model.md
      - Feedback Engine: guide/feedback_engine.md
      - Troubleshooting: guide/troubleshooting.md
  - Admin & Ops:
      - Security Hardening: guide/security_hardening.md
      - Deployment: DEPLOYMENT.md
      - Admin Endpoints: guide/admin_endpoints.md
      - Clustering: CLUSTERING.md
  - Reference:
      - API and Schema: API_AND_SCHEMA.md
      - Hierarchy: HIERARCHY.md
      - Hardware and Models: HARDWARE_AND_MODELS.md
      - Configuration: CONFIGURATION.md
      - Structure: STRUCTURE.md
      - Glossary: GLOSSARY.md
      - Gating Keys: GATING_KEYS.md
      - Memory and Training: MEMORY_AND_TRAINING.md
      - Arrow Ingestion: arrow_ingestion.md
  - Developer:
      - Overview: developer/index.md
      - Status: developer/status.md
      - Tasks: developer/tasks.md
      - Stability Freeze: developer/stability.md
      - CI: developer/ci.md
      - Style: developer/style.md
      - Security: developer/SECURITY.md
      - Windows Compatibility Gate: developer/windows-compat-gate.md
      - Windows Start Validation: developer/windows-start-validation.md
      - Plugin ABI & Trust: developer/plugin_abi_trust.md
      - Contract Tests: developer/contract_tests.md
  - About:
      - Commons Kit: about/commons_kit.md
      - Backlog: BACKLOG.md
      - Roadmap: ROADMAP.md
      - Interface Roadmap: INTERFACE_ROADMAP.md
      - Policy: POLICY.md
      - Project Instructions: PROJECT_INSTRUCTIONS.md
      - Training Research: training_research.md
      - Wiki Structure: wiki_structure.md
