[profile.default]
retries = 0
status-level = "all"
final-status-level = "flaky"
failure-output = "immediate"
fail-fast = true
test-threads = "num-cpus"
slow-timeout = { period = "60s", terminate-after = 1 }

[profile.ci]
retries = 0
status-level = "all"
final-status-level = "flaky"
failure-output = "final"
fail-fast = true
test-threads = "num-cpus"
slow-timeout = { period = "60s", terminate-after = 1 }
run-timeout = "10m"

