[package]
name = "arw-cli"
version = "0.1.2"
edition = "2021"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
arw-core = { path = "../../crates/arw-core", version = "0.1.2" }
serde_json = { workspace = true }
base64 = "0.22"
ed25519-dalek = { version = "2", default-features = false, features = ["std"] }
rand = "0.9"
rand_core = "0.9"
