[package]
name = "arw-protocol"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
schemars = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utoipa = { workspace = true }
