[package]
name = "arw-runtime"
version = "0.1.4"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.90"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
async-trait = "0.1"
