name: "🐛 Bug report"
description: Report a reproducible problem
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `arw-server --version` and OS/arch
      placeholder: e.g., 0.1.0-beta, Linux/arm64
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Copy‑pasteable steps to reproduce, including commands and config
      placeholder: |
        1. ...
        2. ...
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs (redact secrets) or screenshots
      render: shell
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I confirmed docs links are up‑to‑date
        - label: I tried the latest release or `main`
