blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question / start a discussion
    url: https://github.com/t3hw00t/Agent_Hub/discussions
    about: For usage questions or open‑ended ideas

