name: "✨ Feature request"
description: Suggest an idea or improvement
labels: ["type/feat"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What’s the user problem or job‑to‑be‑done?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the change at a high level
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - area/ui
        - area/cli
        - area/service
        - area/docs
        - area/recipes
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Adds/impacts docs (Tutorial/How‑to/Reference/Explanation)
        - label: Has a minimal, testable slice

