// Generated by hand to mirror ARW models typed responses. Keep in sync with OpenAPI.
// Updated: 2025-09-14

export interface ModelsConcurrency {
  configured_max: number;
  available_permits: number;
  held_permits: number;
  hard_cap?: number | null;
}

export interface ModelsMetrics {
  started: number;
  queued: number;
  admitted: number;
  resumed: number;
  canceled: number;
  completed: number;
  completed_cached: number;
  errors: number;
  bytes_total: number;
  ewma_mbps?: number | null;
}

export interface ModelItem {
  id: string;
  provider?: string;
  path?: string;
  sha256?: string;
  bytes?: number;
  status?: string;
  error_code?: string;
}

export interface ModelsSummary {
  items: ModelItem[];
  default: string;
  concurrency: ModelsConcurrency;
  metrics: ModelsMetrics;
}

export interface ActiveJob {
  model_id: string;
  job_id: string;
}

export interface ModelsJobs {
  active: ActiveJob[];
  inflight_hashes: string[];
  concurrency: ModelsConcurrency;
}

export interface HashItem {
  sha256: string;
  bytes: number;
  path: string;
  providers: string[];
}

export interface ModelsHashesPage {
  total: number;
  count: number;
  limit: number;
  offset: number;
  items: HashItem[];
}

