[dist]
# Targets for which cargo-dist will produce archives/installers
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc"
]

[build]
# Universal default to keep peak memory predictable across platforms
# (jobs=1 reduces concurrent rustc processes which can OOM on Windows/MSVC).
jobs = 1
