image:
  repository: ghcr.io/t3hw00t/arw-svc
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

env:
  ARW_PORT: 8090
  ARW_DEBUG: 0
  extra: [] # list of { name: FOO, value: BAR }

resources: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: arw.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

