[package]
name = "arw-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
arw-protocol = { path = "../arw-protocol" }
arw-events = { path = "../arw-events" }
toml = { workspace = true }


inventory = { workspace = true }
schemars = { workspace = true }
jsonschema = { workspace = true }
once_cell = { workspace = true }

# Optional runtime for loading WASM plug‑ins
wasmtime = { version = "36.0.2", optional = true, features = ["component-model"] }
wit-bindgen = { version = "0.45.1", optional = true }

[features]
default = []
wasm = ["wasmtime", "wit-bindgen"]

[dependencies.arrow2]
workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "ingest"
harness = false
