[package]
name = "arw-policy"
version = "0.1.4"
edition = "2021"
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
cedar-policy = { version = "4.6", default-features = false }
