cache:
  # Currently supported fields map directly to environment knobs.
  action_cache:
    ttl: 7d               # -> ARW_TOOLS_CACHE_TTL_SECS (seconds)
    ttl_secs: 604800      # Explicit seconds override when both ttl and ttl_secs set
    capacity: 4096        # -> ARW_TOOLS_CACHE_CAP (entries)
    allow:                # -> ARW_TOOLS_CACHE_ALLOW (CSV)
      - demo.echo
      - http.fetch
    deny:                 # -> ARW_TOOLS_CACHE_DENY (CSV)
      - fs.patch
  read_models:
    sse:
      coalesce_ms: 250    # -> ARW_ROUTE_STATS_COALESCE_MS + ARW_MODELS_METRICS_COALESCE_MS
      idle_publish_ms: 2000  # -> ARW_ROUTE_STATS_PUBLISH_MS + ARW_MODELS_METRICS_PUBLISH_MS

  # Planned sections stay commented until implementation lands.
  # llm:
  #   kv_prefix_cache: on
  #   semantic_cache:
  #     embedder: "bge-small-en"
  #     sim_threshold: 0.92
  #     verifier: "mini-qa-judge"
  #     scope: per-user
  #     negative_cache_ttl: 2h
  # edge:
  #   headers:
  #     cache_control: "public, max-age=60, stale-while-revalidate=300, stale-if-error=86400"
  #   request_coalescing: true
  # compression:
  #   zstd_dictionary:
  #     per_type: [json_tool_output, patches]
  #     train_on: last_10k_samples
