[runtime]
portable = true
state_dir = "%LOCALAPPDATA%/arw"
cache_dir = "%LOCALAPPDATA%/arw/cache"
logs_dir  = "%LOCALAPPDATA%/arw/logs"

[cluster]
enabled = false
# Role and identity (documented; not all fields are wired yet)
# role = "home"            # other: "worker" (default: home)
# node_id = "hostname-or-uuid"

# Bus/Queue defaults; switch to "nats" when deploying a broker
bus = "local"
queue = "local"
# nats_url = "nats://127.0.0.1:4222"

# Egress policy preview & ledger (planned)

# Egress (persisted settings; validated by spec/schemas/egress_settings.json)
# [egress]
# posture = "standard"              # off|public|allowlist|custom (or relaxed|standard|strict)
# allowlist = ["api.github.com"]     # hostnames (exact or use *.suffix in tools/proxy allowlists)
# block_ip_literals = true           # deny IP literal hosts
# dns_guard_enable = true            # deny DoH/DoT endpoints and dns-message payloads
# proxy_enable = true                # start local forward proxy on loopback
# proxy_port = 9080                  # default binding
# ledger_enable = true               # append decisions to kernel egress ledger

# Session sharing (planned; roles: view/suggest/drive)
# share_sessions = false

# Admission and budgets for offload (planned defaults)
# min_mbps = 2.0
# soft_budget_degrade_pct = 80
