# Immutable gating policy (deny always wins)
# Keys support trailing * as prefix wildcard.
# Examples:
#   "events:*"            deny all events
#   "task:math.add"       deny specific task kind
#   "queue:*"             deny all queue operations
#   "runtime:*"           deny managed runtime mutations

deny_user = []

# Production hardening tip:
# Enable this when you want the supervisor APIs available to automation
# but kept off in local builds:
# deny_user = ["runtime:restore", "runtime:stop"]

# Toggle the comment below to disable local introspection endpoints by default.
# deny_user = ["introspect:*"]

# Optional complex contracts (deny with conditions; immutable within window; can auto-renew)
# [[contracts]]
# id = "night-quiet"
# patterns = ["events:*"]
# subject_role = "edge"           # matches local role
# tags_any = ["lab"]              # optional
# valid_from_ms = 0               # start now
# valid_to_ms = 1735776000000     # until a fixed time (ms)
# auto_renew_secs = 0             # or e.g., 3600 to auto-renew hourly
# immutable = true                # deny is immutable within window
