snappy:
  budgets:
    i2f_p95_ms: 50
    first_partial_p95_ms: 150
    cadence_ms: 250
    full_result_p95_ms: 2000
  gating:
    fail_on_regressions: true
    protected_endpoints: ["/admin/debug", "/state/*", "/chat/*", "/events"]
