apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arw-svc.fullname" . }}
  labels:
    {{- include "arw-svc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "arw-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arw-svc.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      {{- end }}
      containers:
        - name: arw-svc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- toYaml .Values.securityContext.container | nindent 12 }}
          {{- end }}
          env:
            - name: ARW_PORT
              value: "{{ .Values.env.ARW_PORT }}"
            - name: ARW_DEBUG
              value: "{{ .Values.env.ARW_DEBUG }}"
            {{- with .Values.env.extra }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.state.enabled }}
          volumeMounts:
            - name: state
              mountPath: {{ .Values.state.mountPath | quote }}
          {{- end }}
      {{- if .Values.state.enabled }}
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: {{ include "arw-svc.fullname" . }}-state
      {{- end }}
