name: CI

on: [push, pull_request]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  fmt_and_docs:
    name: Check fmt & build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: docs
        run: cargo doc --no-deps

  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test --all --verbose

      - name: Run tests (chrono feature)
        run: cargo test --lib chrono --features chrono

      - name: Run tests (serde feature)
        run: cargo test --lib serde --features serde

  semver:
    name: cargo-semver-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2.6
