{{- if and (not .Values.adminToken.existingSecret) .Values.adminToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arw-server.fullname" . }}-admin
  labels:
    {{- include "arw-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ default "ARW_ADMIN_TOKEN" .Values.adminToken.key }}: {{ .Values.adminToken.value | quote }}
{{- end }}

