apiVersion: v1
kind: Service
metadata:
  name: {{ include "arw-server.fullname" . }}
  labels:
    {{- include "arw-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "arw-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

