[package]
name = "arw-macros"
version = "0.2.0-dev"
edition = "2021"
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote       = { workspace = true }
syn         = { workspace = true, features = ["full"] }
