name: Actionlint

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Run actionlint
        uses: rhysd/actionlint@62dc61a45fc95efe8c800af7a557ab0b9165d63b # v1.7.1
