name: Cargo Deny

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CARGO_DENY_VERSION: 0.14.24
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked --version ${{ env.CARGO_DENY_VERSION }}
      - name: Run cargo-deny (advisories, licenses, bans)
        run: |
          cargo deny check advisories bans sources licenses
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
