name: Cargo Deny

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Run cargo-deny (advisories, licenses, bans)
        working-directory: Agent_Hub
        run: |
          cargo deny check advisories bans sources licenses
        continue-on-error: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
