name: CI (nextest)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXTEST_VERSION: 0.9.67
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: Install nextest
        uses: taiki-e/install-action@7ec692fc37da04f8da31c22ba9f3b71ef267e650 # v2
        with:
          tool: nextest
          version: ${{ env.NEXTEST_VERSION }}
      - name: Build tests
        run: cargo nextest run --locked --no-run
      - name: Run tests (CI profile)
        env:
          RUST_BACKTRACE: 1
        run: cargo nextest run --locked --profile ci --workspace
