name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (all targets)
        run: cargo build --workspace --all-targets --locked

      - name: Test
        run: cargo test --workspace --locked

      - name: Package artifact (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: ./scripts/package.ps1

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: arw-windows-bundle
          path: dist/*.zip

      - name: Package artifact (Linux)
        if: runner.os == 'Linux'
        run: bash ./scripts/package.sh --no-build

      - name: Upload artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: arw-linux-bundle
          path: dist/*.zip

