name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CARGO_TERM_COLOR: always
      REPRO_NOW: 1970-01-01T00:00:00Z
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt, clippy

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin pymdown-extensions

      - name: Validate feature registry
        run: python3 scripts/check_feature_integrity.py

      - name: Validate system components registry
        run: python3 scripts/check_system_components_integrity.py

      - name: Generate docs from registries
        run: |
          python3 scripts/gen_feature_matrix.py
          python3 scripts/gen_feature_catalog.py
          python3 scripts/gen_system_components.py

      - name: Ensure generated docs are committed
        run: |
          git add -A
          git diff --cached --name-only
          git diff --cached --quiet || (echo 'error: uncommitted generated docs' && exit 1)

      - name: Build docs (strict)
        run: mkdocs build --strict

      - name: Upload docs artifact (PR preview)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site/

      - name: Rust format
        run: cargo fmt --all --check

      - name: Clippy (workspace)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: EnvGuard style check
        env:
          ENFORCE_ENV_GUARD: 1
        run: bash scripts/check_env_guard.sh

      - name: Event kind lint
        run: python3 scripts/lint_event_names.py

      - name: Ensure OpenAPI summaries
        run: python3 scripts/check_operation_docs_sync.py

      - name: Tests (workspace)
        run: cargo nextest run --workspace

      - name: Snappy bench (sanity)
        run: bash scripts/ci_snappy_bench.sh

      - name: Trial triad smoke
        run: bash scripts/triad_smoke.sh

      - name: Trial context telemetry check
        run: bash scripts/context_ci.sh

      - name: Runtime llama smoke (stub)
        env:
          MODE: stub
        run: bash scripts/runtime_llama_smoke.sh

      - name: Legacy surface guard
        env:
          ARW_LEGACY_CHECK_WAIT_SECS: 120
        run: bash scripts/check_legacy_surface.sh
