name: Dist

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

jobs:
  release-gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    steps:
      - name: Check restructure release blockers
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const label = 'release-blocker:restructure';
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner,
              repo,
              state: 'open',
              labels: label,
              per_page: 100,
            });
            if (issues.length > 0) {
              const refs = issues.map(issue => `#${issue.number} (${issue.title})`).join(', ');
              core.setFailed(`Open restructure release blockers: ${refs}`);
            } else {
              core.info('No open restructure release blockers.');
            }

  build-installers:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    env:
      CARGO_DIST_VERSION: 0.12.0
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: Install Tauri (WebKitGTK) deps (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config \
            libgtk-3-dev libglib2.0-dev libgdk-pixbuf2.0-dev libpango1.0-dev libatk1.0-dev libcairo2-dev
          sudo apt-get install -y libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev \
            || sudo apt-get install -y libwebkit2gtk-4.0-dev libjavascriptcoregtk-4.0-dev libsoup2.4-dev
      - name: Cache cargo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-dist
        run: cargo install cargo-dist --locked --version ${{ env.CARGO_DIST_VERSION }}
      - name: Build installers
        run: cargo dist build --target ${{ matrix.target }} --installer --no-confirm
      - name: Upload installers
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ matrix.target }}-dist
          path: target/dist/*

  docs-wheel-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      PIP_VERSION: 24.2
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'

      - name: Install pip-tools
        run: python -m pip install "pip==${PIP_VERSION}" pip-tools

      - name: Build docs wheels archive
        run: bash scripts/build_docs_wheels.sh --archive dist/docs-wheels.tar.gz

      - name: Upload docs wheels
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: docs-wheels
          path: dist/docs-wheels.tar.gz

  release:
    needs: [release-gate, build-installers, docs-wheel-cache]
    runs-on: ubuntu-latest
    environment:
      name: releases
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v4
        with:
          path: dist
      - name: List artifacts
        run: ls -R dist || true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5 # v2
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
