name: Docker Images (manual, arw-server)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-arw-server:
    name: Build arw-server (no push)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push) arw-server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/arw-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
