name: Docker Images (manual)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-arw-svc:
    name: Build arw-svc (no push)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: Agent_Hub
          file: Agent_Hub/apps/arw-svc/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
