name: Docs Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Rust (for docgen)
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@7939da402645ba29a2df566723491a2c856e8f8a # v2
        with:
          workspaces: |
            . -> target

      - name: Generate docs/status + tasks and specs (docgen)
        run: |
          bash scripts/docgen.sh
          # Ensure generated artifacts are committed
          set -e
          if ! git diff --quiet -- docs/developer/status.md docs/developer/tasks.md spec/asyncapi.yaml spec/mcp-tools.json; then
            echo '::error::Docgen artifacts changed. Run scripts/docgen.sh and commit the updates.'
            git --no-pager diff -- docs/developer/status.md docs/developer/tasks.md spec/asyncapi.yaml spec/mcp-tools.json | sed -n '1,200p'
            exit 1
          fi

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.x'

      - name: Cache pip (docs)
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('requirements/docs.txt') }}

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/docs.txt

      - name: Run docs check (build + lint)
        run: bash scripts/docs_check.sh
