name: Docs

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'site/**'
      - 'spec/**'
  workflow_dispatch:

concurrency:
  group: "docs-site"
  cancel-in-progress: true

jobs:
  build-and-commit-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Rust (for docgen)
        uses: dtolnay/rust-toolchain@stable

      - name: Install docgen deps (jq)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate workspace status page
        run: bash ./scripts/docgen.sh

      - name: Generate OpenAPI spec
        run: |
          cargo build -p arw-svc --release --locked
          OPENAPI_OUT=spec/openapi.yaml ./target/release/arw-svc || true

      - name: Install mkdocs
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build docs (into ./site)
        run: mkdocs build --strict

      - name: Commit updated site and spec to main
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git add site spec || true
          if ! git diff --cached --quiet; then
            git commit -m "docs(site): update generated site and spec"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
