name: Docs

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Rust (for docgen)
        uses: dtolnay/rust-toolchain@stable

      - name: Install docgen deps (jq)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate workspace status page
        run: bash ./scripts/docgen.sh

      - name: Generate OpenAPI spec
        run: |
          cargo build -p arw-svc --release --locked
          OPENAPI_OUT=spec/openapi.yaml ./target/release/arw-svc || true

      - name: Install mkdocs
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build docs
        run: mkdocs build --strict

      - name: Upload spec artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spec
          path: spec/*

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
