name: Docs build and deploy

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy docs to gh-pages with mike'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs + plugins
        run: |
          pip install --upgrade pip
          pip install mkdocs-material mike git-python mkdocs-git-revision-date-localized-plugin
      - name: Build docs
        run: mkdocs build --strict

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy == 'true' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs + mike
        run: |
          pip install mkdocs-material mike git-python mkdocs-git-revision-date-localized-plugin
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Deploy latest
        run: |
          mike deploy --push --update-aliases latest
          mike set-default --push latest

  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs
        run: |
          pip install mkdocs-material mkdocs mkdocs-git-revision-date-localized-plugin
      - name: Build docs
        run: mkdocs build --strict
      - name: Serve docs
        run: |
          nohup python3 -m http.server 8000 -d site >/dev/null 2>&1 &
          sleep 2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Axe a11y (optional)
        continue-on-error: true
        run: |
          bash scripts/ci_run_axe.sh http://127.0.0.1:8000 a11y-reports
      - name: Upload a11y reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: site-a11y-reports
          path: a11y-reports
