name: Sync labels

on:
  push:
    branches: [ main, master ]
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  pull_request:
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  sync:
    permissions:
      contents: read
      issues: write
      metadata: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          dry-run: ${{ github.event_name == 'pull_request' }}
