name: Sync labels

on:
  push:
    branches: [ main, master ]
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  pull_request:
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  workflow_dispatch: {}

jobs:
  sync:
    permissions:
      contents: read
      issues: write
      metadata: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
