name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lychee:
    name: Check docs links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Run lychee
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1
        with:
          # Use repo-configured exclusions and headers
          args: --config .lychee.toml --no-progress --verbose docs/**/*.md README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
