name: Link check (docs + README)

on:
  pull_request:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.lychee.toml'
  workflow_dispatch: {}

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lychee link check
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose --no-progress
            --config .lychee.toml
            README.md docs/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

