name: Release Packages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux:
    name: package (linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            Agent_Hub

      - name: Build native (x86_64)
        run: |
          cd Agent_Hub
          cargo build --release -p arw-svc -p arw-cli --locked || true
          bash scripts/package.sh

      - name: Install Linux ARM64 cross toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build cross (aarch64-unknown-linux-gnu)
        env:
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: |
          cd Agent_Hub
          rustup target add aarch64-unknown-linux-gnu
          cargo build --release -p arw-svc -p arw-cli --target aarch64-unknown-linux-gnu --locked || true
          bash scripts/package.sh --no-build --target aarch64-unknown-linux-gnu

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Agent_Hub/dist/*.zip

  windows:
    name: package (windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            Agent_Hub

      - name: Build native (x86_64)
        shell: pwsh
        run: |
          Set-Location Agent_Hub
          cargo build --release -p arw-svc -p arw-cli --locked
          ./scripts/package.ps1

      - name: Build cross (aarch64-pc-windows-msvc)
        shell: pwsh
        run: |
          Set-Location Agent_Hub
          rustup target add aarch64-pc-windows-msvc
          cargo build --release -p arw-svc -p arw-cli --target aarch64-pc-windows-msvc --locked
          ./scripts/package.ps1 -NoBuild -Target aarch64-pc-windows-msvc

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Agent_Hub/dist/*.zip

  macos:
    name: package (macos)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            Agent_Hub

      - name: Build native
        run: |
          cd Agent_Hub
          cargo build --release -p arw-svc -p arw-cli --locked || true
          bash scripts/package.sh

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Agent_Hub/dist/*.zip

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

