name: Runtime Smoke Matrix

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  runtime-smoke:
    name: Runtime smoke (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: runtime-smoke-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run runtime smoke suite
        env:
          RUNTIME_SMOKE_GPU_POLICY: simulate
          RUNTIME_SMOKE_REQUIRE_LOOPBACK: 0
        run: |
          set -euo pipefail
          . scripts/smoke_safe.sh
          bash scripts/runtime_smoke_suite.sh
