name: TS Client Publish

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'ts-client-v*'

jobs:
  build-publish:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/ts-client-v') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Node info
        run: |
          node -v
          npm -v

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: arw-client-npm-pack
          path: clients/typescript/*.tgz

      - name: Publish to npm (if token present)
        if: ${{ secrets.NPM_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: No NPM token, skipping publish
        if: ${{ secrets.NPM_TOKEN == '' }}
        run: echo "NPM_TOKEN not set; skipping publish." && exit 0
