name: TS Client Publish

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type publish to confirm npm release'
        required: false
        default: ''
  push:
    tags:
      - 'ts-client-v*'

permissions:
  contents: read
  actions: write

jobs:
  build-publish:
    if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ts-client-v')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'publish') }}
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    defaults:
      run:
        working-directory: clients/typescript
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Node info
        run: |
          node -v
          npm -v

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack

      - name: Upload package artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: arw-client-npm-pack
          path: clients/typescript/*.tgz

      - name: Publish to npm (if token present)
        if: ${{ env.NPM_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
        run: npm publish --access public

      - name: No NPM token, skipping publish
        if: ${{ env.NPM_TOKEN == '' }}
        run: |
          echo "::error::NPM_TOKEN not set; aborting publish."
          exit 1
