name: windows-advanced-gate

on:
  workflow_dispatch:
    inputs:
      strict_sign:
        description: "Fail if unsigned binaries/installers are found"
        required: false
        default: "false"
  release:
    types: [published]

permissions:
  contents: read

jobs:
  advanced-gate:
    name: advanced-gate (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
        with:
          workspaces: |
            .

      - name: Build arw-server (release)
        shell: pwsh
        run: |
          cargo build --release -p arw-server --locked

      - name: Run Windows Advanced Gate (informational by default)
        shell: pwsh
        env:
          ARW_STRICT_SIGN_VERIFY: ${{ inputs.strict_sign }}
        run: |
          ./scripts/windows-advanced-gate.ps1
